config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :orders
  resources :kategoris
  resources :makanans
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'YABB', root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "Makanan", makanans_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Order", orders_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Kategori", kategoris_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Customers", customers_path, class:"nav-link" %>
      </li>



      
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/index.html.erb
<h1>YABB FINAL TEST</h1>
<p>Family Catering app with rails :)</p>