config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :orders
  resources :kategoris
  resources :makanans
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/kategori.rb
class Kategori < ApplicationRecord
  has_one :makanan
end

app/controllers/kategoris_controller.rb
class KategorisController < ApplicationController
  before_action :set_kategori, only: %i[ show edit update destroy ]

  # GET /kategoris or /kategoris.json
  def index
    @kategoris = Kategori.all
  end

  # GET /kategoris/1 or /kategoris/1.json
  def show
  end

  # GET /kategoris/new
  def new
    @kategori = Kategori.new
  end

  # GET /kategoris/1/edit
  def edit
  end

  # POST /kategoris or /kategoris.json
  def create
    @kategori = Kategori.new(kategori_params)

    respond_to do |format|
      if @kategori.save
        format.html { redirect_to kategori_url(@kategori), notice: "Kategori was successfully created." }
        format.json { render :show, status: :created, location: @kategori }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kategoris/1 or /kategoris/1.json
  def update
    respond_to do |format|
      if @kategori.update(kategori_params)
        format.html { redirect_to kategori_url(@kategori), notice: "Kategori was successfully updated." }
        format.json { render :show, status: :ok, location: @kategori }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kategoris/1 or /kategoris/1.json
  def destroy
    @kategori.destroy

    respond_to do |format|
      format.html { redirect_to kategoris_url, notice: "Kategori was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kategori
      @kategori = Kategori.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kategori_params
      params.require(:kategori).permit(:nama_kategori)
    end
end

app/helpers/kategoris_helper.rb
module KategorisHelper
end

app/views/kategoris/_form.html.erb
<%= form_with(model: kategori) do |form| %>
  <% if kategori.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kategori.errors.count, "error") %> prohibited this kategori from being saved:</h2>

      <ul>
        <% kategori.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nama_kategori, style: "display: block" %>
    <%= form.text_field :nama_kategori %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kategoris/_kategori.html.erb
<div id="<%= dom_id kategori %>">
  <p>
    <strong>Nama kategori:</strong>
    <%= kategori.nama_kategori %>
  </p>

</div>

app/views/kategoris/edit.html.erb
<h1>Editing kategori</h1>

<%= render "form", kategori: @kategori %>

<br>

<div>
  <%= link_to "Show this kategori", @kategori %> |
  <%= link_to "Back to kategoris", kategoris_path %>
</div>

app/views/kategoris/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Kategoris</h1>

<div id="kategoris">
  <% @kategoris.each do |kategori| %>
    <%= render kategori %>
    <p>
      <%= link_to "Show this kategori", kategori %>
    </p>
  <% end %>
</div>

<%= link_to "New kategori", new_kategori_path %>

app/views/kategoris/new.html.erb
<h1>New kategori</h1>

<%= render "form", kategori: @kategori %>

<br>

<div>
  <%= link_to "Back to kategoris", kategoris_path %>
</div>

app/views/kategoris/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kategori %>

<div>
  <%= link_to "Edit this kategori", edit_kategori_path(@kategori) %> |
  <%= link_to "Back to kategoris", kategoris_path %>

  <%= button_to "Destroy this kategori", @kategori, method: :delete %>
</div>